services:
  python:
    build: .
    container_name: python-etl  #nomear o container foi um exemplo para a primeira aula, mas normalmente deixamos o compose gerenciar isso e dar nomes automaticamte
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    working_dir: /app
  postgres:
    image: postgres:17          #aqui usamos a versão do postgres 17 para simplifiar, mas para um .yaml em produção o ideal é especificar mais a versão, como "postgres:17.7" por exemplo, para evitar conflitos de versões entre as pessoas que vão usar o ambiente
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: etl
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

